### ISSUE TITLE
Clarification on search assets by name

### ISSUE THREAD

**Issue by zuzzurro** [Azure/Azure-Media-Services-Explorer#47]
Hi Xavier
Can you confirm that searching assets by name is ultimately limited by the maximum number of pages available in the Assets tab and that this limit is set at 20?
(I that 20 is a limit because if I filter "All" assets that is the number of pages, and it seems too round a number to be the real one..)

**Comment by xpouyat** [comment]
Hi,
Actually, the limit of returned results is 1000. In options, the default number of items per page is 50, so that's why you see 20 pages.
The limit of 1000 comes from the maximum of assets returned by a single query. It can be increased by doing multiple query in the code (this is what happening for the "delete all assets" features).
Do you need more assets to be displayed? I am currently working on updating the code to support "all visible assets" as an input for some processes. With such option, up to 1000 assets could be processed (encoded, indexed, etc) at the same time from the tool.

**Comment by zuzzurro** [comment]
The issue is that if I search for an asset, I really mean to find the asset. And if I get nothing back I assume that the asset I am looking for does not exist, not that because of paging or query limitation the asset is out of reach...
I have a customer right now (you know about them) that create a lot of programs on a 24/7 basis. It's very easy for a particular asset to go beyond this event horizon and fall in the black hole.
People tell me that it works on the web page, I would prefer not to have to use that if can use this tool all the time.

**Comment by xpouyat** [comment]
If you get nothing with "Filter:All" and "Status:All", then the asset you search does not exist. If you set Filter:All , the first 1000 results of the query are reported, which means the result is truncated, but if the number of assets is less than 1000, then it means the result is complete.
Do you search for a program with program id or asset id? It is not possible to search for program id in the asset tab (I could add the option) and the live tab does not have paging....

**Comment by zuzzurro** [comment]
OK, I am pretty sure that the item I was looking for has to exist for various reasons, and I was not sure about the way the search works, that's why I asked. I will double check tomorrow.

**Comment by xpouyat** [comment]
I looked to the code for the queries and it is possible that some queries missed assets. The reason is because I used .ToList() in some upper query that could filter the assets or files and truncate the final results if you have more than 1000 assets in the acount. I updated the code and I can share a build with you. Please send me an email to xpouyat @ Microsoft.com

**Comment by zuzzurro** [comment]
No, it's still not working (for me). Let me explain, I have 9 channels and on each channel i have at least one program running forever (forever right now is about 15 days, but in theory they should be running since June). If I go in the Live view I can see the the programs and I can see the related asset information (name). If I then search for that name in the asset tab (Search in asset name), it doesn't return anything. (Alsoif I search by asset id, nb:cid:UUID:dac53a5d-1500-80c4-4372-f1e565092f8f).
Filters are: All All
Is a partial match accepted in the name , btw?

**Comment by xpouyat** [comment]
Partial match is accepted. You can search in asset Id:
dac53a5d
or
dac53a5d-1500-80c4-4372-f1e565092f8f
or
nb:cid:UUID:dac53a5d-1500-80c4-4372-f1e565092f8f
(all are supported).

It is strange that you don't find the related asset. Be careful, you have a program id and an asset id (different) for each program.

**Comment by xpouyat** [comment]
On the program, if you open the related asset, do you see the files? The asset is not marked as deleted, I suppose?
